;*********************  Definição do processador *****************************

			#include p16F877A.inc 
			__config _HS_OSC & _WDT_OFF & _LVP_OFF & _PWRTE_ON 

;************************** Memória de programa ******************************
 			cblock 0x3C
				c1 ; VARIAVES DE CADA NUMERO (SENHA SEIS DIGITOS)
				c2
				c3
				c4
				c5
				c6
				OPERACAO ; VARIAVEL DE OPERACAO PARA SABER SE IRA DESTRAVAR OU MUDAR SENHA
				CONTROL ; VARIAVEL AUXILIAR EM LACOS DE REPETICAO
				MAX_TENTATIVA ; VARIAVEL PARA CONTAR AS TENTATIVAS ERRADAS
				DELAY ; VARIAVES DA FUNCAO PERDE_TEMPO
				VEZES
			endc
			ORG	0 

RESET 		nop             
 			goto START 

;***************************** Interrupção **********************************
 			ORG 4 

;*************************** Inicio do programa ******************************
CONVERTER


START		bsf STATUS,RP0    ;Vai para o Bank1 de memória
			movlw b'00000000' ;Gravando em W todos os pinos como saida
			movwf TRISD		  ; Configura TRISD com o valor de W, QUAIS LEDS NO DISPLAY SERAO ACESOS
			movlw b'00000000' 
			movwf TRISA		; TRISD COM PINOS DE SAIDA, SELECAO DE QUAL DISPLAY ACENDER
			movlw b'00001111' ; TRISA COM 4 PINOS PARA ENTRADA (TECLADO MATRICIAL)
			movwf TRISB
			movlw b'00000000' ; BUZZER
			movwf TRISE
			movlw b'00000000' ; PORTS ONDE O MOTOR ESTA LIGADO
			movwf TRISC
			MOVLW 0 ;ZERANDO AS VARIAVES E SENHA PADRAO - 000000
			MOVWF c1
			MOVWF c2		
			MOVWF c3
			MOVWF c4
			MOVWF c5
			MOVWF c6
			MOVWF OPERACAO
			MOVWF MAX_TENTATIVA


			bcf STATUS, RP0 ;BANK 0
			GOTO INICIO
INICIO
			MOVLW D'255'
			MOVWF CONTROL ; SEMPRE QUE VOLTAR AO INICIO DEVE NOVAMENTE ADCIONAR O VALOR EM CONTROL, POIS SERA UTILIZADA EM DIVERSOS LACOS DE REPETICAO
			CLRF PORTD ; LIMPANDO OS POORTS
			CLRF PORTA
			CLRF PORTC
			MOVLW b'00000001' ; DESLIGANDO O BUZZER CASO ESTEJA LIGADO
			MOVWF PORTE
			GOTO CHECA_FUNC
CHECA_FUNC
			MOVLW b'00100000' ; CHECANDO O MENU
			MOVWF PORTA
			MOVLW b'00111111' ; EXIBINDO "O" DE On
			MOVWF PORTD
			CALL PERDE_TEMPO_MENOR
			CLRF PORTD ;LIMPANDO APOS UM TEMPO
			CLRF PORTA

			MOVLW b'00010000' ; EXIBINDO "n" DE On NO DISPLAY SEQUENTE
			MOVWF PORTA
			MOVLW b'01010100'
			MOVWF PORTD
			CALL PERDE_TEMPO_MENOR
			CLRF PORTD ; LIMPANDO APOS UM TEMPO
			CLRF PORTA

			movlw b'01111111' ; CHECANDO OS BOTOES DE FUNCAO, C - PARA ABRIR E D - PARA MUDAR SENHA
			movwf PORTB
			BTFSS PORTB, 0
			GOTO DESBLOQ; ABRIR COFRE
			BTFSS PORTB, 1
			GOTO MUDA_SENHA ; MUDAR SENHA
			GOTO CHECA_FUNC; CONTINUAR AGUARDANDO UMA TECLA SER PRESSIONADA
DESBLOQ
			BTFSS PORTB, 0
			GOTO DESBLOQ ; ESPERANDO O USUARIO SOLTAR O BOTAO PARA NAO BUGAR
			CALL PERDE_TEMPO
			movlw b'00000000'; APITANDO RAPIDAMENTE NO BUZZER PARA SIMBOLIZAR QUE O COMANDO FOI RECONHECIDO
			movwf PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			MOVLW D'0' ; OPERACAO ZERO, SERVE PARA DIZER QUE SERA ABERTO O COFRE, NECESSARIO POIS TANTO MUDAR A SENHA QUANTO ABRIR O COFRE USAM A MESMA FUNCAO DE CHECAGEM DE SENHA
			MOVWF OPERACAO
			GOTO CHAVE1; PRIMEIRO NUMERO DA SENHA

MUDA_SENHA
			BTFSS PORTB, 1
			GOTO MUDA_SENHA ; ESPERANDO O USUARIO SOLTAR O BOTAO PARA NAO BUGAR
			CALL PERDE_TEMPO
			movlw b'00000000' ; APITANDO RAPIDAMENTE NO BUZZER PARA SIMBOLIZAR QUE O COMANDO FOI RECONHECIDO
			movwf PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			MOVLW D'1' ; OPERACAO UM, SERVE PARA DIZER QUE SERA MUDADO A SENHA, NECESSARIO POIS TANTO MUDAR A SENHA QUANTO ABRIR O COFRE USAM A MESMA FUNCAO DE CHECAGEM DE SENHA
			MOVWF OPERACAO
			GOTO CHAVE1 ; PRIMEIRO NUMERO DA SENHA



CHAVE1
			movlw b'11101111' ; TODAS AS FUNCOES INDEPENDENTE DE QUAL PARTE DA SENHA, USAM A MESMA LOGICA
			movwf PORTB
			BTFSS PORTB, 0 ; CHECANDO OS BOTOES ATE O USUARIO PRESSIONAR UM
		GOTO VALOR0_CHAVE1 ; INDO PARA CONTABILIZAR O VALOR APERTADO (NESSE CASO, 0) E COMPARAR COM O PRIMEIRO NUMERO DA SENHA
			BTFSS PORTB, 1
		GOTO VALOR1_CHAVE1
			BTFSS PORTB, 2
		GOTO VALOR2_CHAVE1
			BTFSS PORTB, 3
		GOTO VALOR3_CHAVE1
	
			movlw b'11011111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR4_CHAVE1
			BTFSS PORTB, 1
		GOTO VALOR5_CHAVE1
			BTFSS PORTB, 2
		GOTO VALOR6_CHAVE1
			BTFSS PORTB, 3
		GOTO VALOR7_CHAVE1

			movlw b'10111111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR8_CHAVE1
			BTFSS PORTB, 1
		GOTO VALOR9_CHAVE1
			GOTO CHAVE1

VALOR0_CHAVE1
			BTFSS PORTB, 0 
			GOTO VALOR0_CHAVE1 ; AGUARDANDO USUARIO SOLTAR A TECLA, EVITANDO BUGS
			CALL PERDE_TEMPO
			movlw b'00000000' ; TODAS AS FUNCOES DE CHECAGEM POSSUEM A MESMA LOGICA, APENAS MUDANDO O VALOR QUE SERA COMPARADO E QUAL NUMERO DA SENHA DE 6 NUMEROS
			movwf PORTE ; CONFIRMACAO PELO BUZZER
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000' ; EXIBE UM RISCO NO DISPLAY, PARA MANTER A SENHA EM SIGILO
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'0' ; CHECANDO SE O VALOR PRESSIONADO SERA IGUAL AO VALOR DA SENHA
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG ; CASO PRESSIONADO ERRADO, IR PARA CONTABILIZACAO DO ERRO
			GOTO CHAVE2 ; CASO CERTO, CHECAR PROXIMO DIGITO DA SENHA
VALOR1_CHAVE1
			BTFSS PORTB, 1
			GOTO VALOR1_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'1'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2
VALOR2_CHAVE1
			BTFSS PORTB, 2
			GOTO VALOR2_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'2'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2
VALOR3_CHAVE1
			BTFSS PORTB, 3
			GOTO VALOR3_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'3'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2
VALOR4_CHAVE1
			BTFSS PORTB, 0
			GOTO VALOR4_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'4'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2
VALOR5_CHAVE1
			BTFSS PORTB, 1
			GOTO VALOR5_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'5'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2

VALOR6_CHAVE1
			BTFSS PORTB, 2
			GOTO VALOR6_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'6'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2
VALOR7_CHAVE1
			BTFSS PORTB, 3
			GOTO VALOR7_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'7'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2
VALOR8_CHAVE1
			BTFSS PORTB, 0
			GOTO VALOR8_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'8'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2
VALOR9_CHAVE1
			BTFSS PORTB, 1
			GOTO VALOR9_CHAVE1
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00100000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'9'
			subwf c1, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE2

CHAVE2
			

			movlw b'11101111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR0_CHAVE2
			BTFSS PORTB, 1
		GOTO VALOR1_CHAVE2
			BTFSS PORTB, 2
		GOTO VALOR2_CHAVE2
			BTFSS PORTB, 3
		GOTO VALOR3_CHAVE2
	
			movlw b'11011111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR4_CHAVE2
			BTFSS PORTB, 1
		GOTO VALOR5_CHAVE2
			BTFSS PORTB, 2
		GOTO VALOR6_CHAVE2
			BTFSS PORTB, 3
		GOTO VALOR7_CHAVE2

			movlw b'10111111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR8_CHAVE2
			BTFSS PORTB, 1
		GOTO VALOR9_CHAVE2
		GOTO CHAVE2

VALOR0_CHAVE2
			BTFSS PORTB, 0
			GOTO VALOR0_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'0'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3
VALOR1_CHAVE2
			BTFSS PORTB, 1
			GOTO VALOR1_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'1'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3
VALOR2_CHAVE2
			BTFSS PORTB, 2
			GOTO VALOR2_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'2'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3
VALOR3_CHAVE2
			BTFSS PORTB, 3
			GOTO VALOR3_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'3'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3
VALOR4_CHAVE2
			BTFSS PORTB, 0
			GOTO VALOR4_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'4'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3
VALOR5_CHAVE2
			BTFSS PORTB, 1
			GOTO VALOR5_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'5'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3

VALOR6_CHAVE2
			BTFSS PORTB, 2
			GOTO VALOR6_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'6'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3
VALOR7_CHAVE2
			BTFSS PORTB, 3
			GOTO VALOR7_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'7'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3
VALOR8_CHAVE2
			BTFSS PORTB, 0
			GOTO VALOR8_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'8'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3
VALOR9_CHAVE2
			BTFSS PORTB, 1
			GOTO VALOR9_CHAVE2
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00010000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'9'
			subwf c2, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE3

CHAVE3
			

			movlw b'11101111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR0_CHAVE3
			BTFSS PORTB, 1
		GOTO VALOR1_CHAVE3
			BTFSS PORTB, 2
		GOTO VALOR2_CHAVE3
			BTFSS PORTB, 3
		GOTO VALOR3_CHAVE3
	
			movlw b'11011111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR4_CHAVE3
			BTFSS PORTB, 1
		GOTO VALOR5_CHAVE3
			BTFSS PORTB, 2
		GOTO VALOR6_CHAVE3
			BTFSS PORTB, 3
		GOTO VALOR7_CHAVE3

			movlw b'10111111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR8_CHAVE3
			BTFSS PORTB, 1
		GOTO VALOR9_CHAVE3
		GOTO CHAVE3

VALOR0_CHAVE3
			BTFSS PORTB, 0
			GOTO VALOR0_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'0'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4
VALOR1_CHAVE3
			BTFSS PORTB, 1
			GOTO VALOR1_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'1'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

VALOR2_CHAVE3
			BTFSS PORTB, 2
			GOTO VALOR2_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'2'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

VALOR3_CHAVE3
			BTFSS PORTB, 3
			GOTO VALOR3_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'3'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

VALOR4_CHAVE3
			BTFSS PORTB, 0
			GOTO VALOR4_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'4'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

VALOR5_CHAVE3
			BTFSS PORTB, 1
			GOTO VALOR5_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'5'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

VALOR6_CHAVE3
			BTFSS PORTB, 2
			GOTO VALOR6_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'6'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

VALOR7_CHAVE3
			BTFSS PORTB, 3
			GOTO VALOR7_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'7'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

VALOR8_CHAVE3
			BTFSS PORTB, 0
			GOTO VALOR8_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'8'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

VALOR9_CHAVE3
			BTFSS PORTB, 1
			GOTO VALOR9_CHAVE3
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00001000'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'9'
			subwf c3, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE4

CHAVE4
			

			movlw b'11101111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR0_CHAVE4
			BTFSS PORTB, 1
		GOTO VALOR1_CHAVE4
			BTFSS PORTB, 2
		GOTO VALOR2_CHAVE4
			BTFSS PORTB, 3
		GOTO VALOR3_CHAVE4
	
			movlw b'11011111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR4_CHAVE4
			BTFSS PORTB, 1
		GOTO VALOR5_CHAVE4
			BTFSS PORTB, 2
		GOTO VALOR6_CHAVE4
			BTFSS PORTB, 3
		GOTO VALOR7_CHAVE4

			movlw b'10111111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR8_CHAVE4
			BTFSS PORTB, 1
		GOTO VALOR9_CHAVE4
		GOTO CHAVE4

VALOR0_CHAVE4
			BTFSS PORTB, 0
			GOTO VALOR0_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'0'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5
VALOR1_CHAVE4
			BTFSS PORTB, 1
			GOTO VALOR1_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'1'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5

VALOR2_CHAVE4
			BTFSS PORTB, 2
			GOTO VALOR2_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'2'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5

VALOR3_CHAVE4
			BTFSS PORTB, 3
			GOTO VALOR3_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'3'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5

VALOR4_CHAVE4
			BTFSS PORTB, 0
			GOTO VALOR4_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'4'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5

VALOR5_CHAVE4
			BTFSS PORTB, 1
			GOTO VALOR5_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'5'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5

VALOR6_CHAVE4
			BTFSS PORTB, 2
			GOTO VALOR6_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'6'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5

VALOR7_CHAVE4
			BTFSS PORTB, 3
			GOTO VALOR7_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'7'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5

VALOR8_CHAVE4
			BTFSS PORTB, 0
			GOTO VALOR8_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'8'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5

VALOR9_CHAVE4
			BTFSS PORTB, 1
			GOTO VALOR9_CHAVE4
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000100'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'9'
			subwf c4, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE5
CHAVE5
			

			movlw b'11101111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR0_CHAVE5
			BTFSS PORTB, 1
		GOTO VALOR1_CHAVE5
			BTFSS PORTB, 2
		GOTO VALOR2_CHAVE5
			BTFSS PORTB, 3
		GOTO VALOR3_CHAVE5
	
			movlw b'11011111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR4_CHAVE5
			BTFSS PORTB, 1
		GOTO VALOR5_CHAVE5
			BTFSS PORTB, 2
		GOTO VALOR6_CHAVE5
			BTFSS PORTB, 3
		GOTO VALOR7_CHAVE5

			movlw b'10111111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR8_CHAVE5
			BTFSS PORTB, 1
		GOTO VALOR9_CHAVE5
		GOTO CHAVE5

VALOR0_CHAVE5
			BTFSS PORTB, 0
			GOTO VALOR0_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'0'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6
VALOR1_CHAVE5
			BTFSS PORTB, 1
			GOTO VALOR1_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'1'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

VALOR2_CHAVE5
			BTFSS PORTB, 2
			GOTO VALOR2_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'2'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

VALOR3_CHAVE5
			BTFSS PORTB, 3
			GOTO VALOR3_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'3'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

VALOR4_CHAVE5
			BTFSS PORTB, 0
			GOTO VALOR4_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'4'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

VALOR5_CHAVE5
			BTFSS PORTB, 1
			GOTO VALOR5_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'5'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

VALOR6_CHAVE5
			BTFSS PORTB, 2
			GOTO VALOR6_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'6'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

VALOR7_CHAVE5
			BTFSS PORTB, 3
			GOTO VALOR7_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'7'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

VALOR8_CHAVE5
			BTFSS PORTB, 0
			GOTO VALOR8_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'8'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

VALOR9_CHAVE5
			BTFSS PORTB, 1
			GOTO VALOR9_CHAVE5
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000010'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'9'
			subwf c5, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO CHAVE6

CHAVE6
			

			movlw b'11101111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR0_CHAVE6
			BTFSS PORTB, 1
		GOTO VALOR1_CHAVE6
			BTFSS PORTB, 2
		GOTO VALOR2_CHAVE6
			BTFSS PORTB, 3
		GOTO VALOR3_CHAVE6
	
			movlw b'11011111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR4_CHAVE6
			BTFSS PORTB, 1
		GOTO VALOR5_CHAVE6
			BTFSS PORTB, 2
		GOTO VALOR6_CHAVE6
			BTFSS PORTB, 3
		GOTO VALOR7_CHAVE6

			movlw b'10111111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO VALOR8_CHAVE6
			BTFSS PORTB, 1
		GOTO VALOR9_CHAVE6
		GOTO CHAVE6

VALOR0_CHAVE6
			BTFSS PORTB, 0
			GOTO VALOR0_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'0'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE
VALOR1_CHAVE6
			BTFSS PORTB, 1
			GOTO VALOR1_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'1'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

VALOR2_CHAVE6
			BTFSS PORTB, 2
			GOTO VALOR2_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'2'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

VALOR3_CHAVE6
			BTFSS PORTB, 3
			GOTO VALOR3_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'3'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

VALOR4_CHAVE6
			BTFSS PORTB, 0
			GOTO VALOR4_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'4'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

VALOR5_CHAVE6
			BTFSS PORTB, 1
			GOTO VALOR5_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'5'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

VALOR6_CHAVE6
			BTFSS PORTB, 2
			GOTO VALOR6_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'6'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

VALOR7_CHAVE6
			BTFSS PORTB, 3
			GOTO VALOR7_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'7'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

VALOR8_CHAVE6
			BTFSS PORTB, 0
			GOTO VALOR8_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'8'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

VALOR9_CHAVE6
			BTFSS PORTB, 1
			GOTO VALOR9_CHAVE6
			CALL PERDE_TEMPO
			movlw b'00000000'
			movwf PORTE
			CALL PERDE_TEMPO
			MOVLW b'00000001'
			MOVWF PORTE
			movlw b'00000001'
			movwf PORTA	
			movlw b'01000000'
			movwf PORTD
			MOVLW D'9'
			subwf c6, 0
			BTFSS STATUS, Z
			GOTO WRONG
			GOTO OPEN_COFRE

OPEN_COFRE ; CASO OS SEIS DIGITOS ESTEJAM PRESSIONADOS CORRETAMENTE, ESSA FUNCAO SERA ATIVADA
			CLRF MAX_TENTATIVA; LIMPANDO CASO TENHA HAVIDO TENTATIVAS ERRADAS ANTERIORMENTE
			movlw b'00000000' ; CONFIRMACAO DE DOIS BIPS NO BUZZER, SIMBOLIZANDO QUE A SENHA FOI CORRETAMENTE DIGITADA
			MOVWF PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			movlw b'00000001'
			MOVWF PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			movlw b'00000000'
			MOVWF PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			movlw b'00000001'
			MOVWF PORTE
			CLRF PORTD ; LIMPANDO OS DISPLAYS
			CLRF PORTA
			MOVLW D'1' ; CHECANDO SE A OPERACAO E DE ABRIR O COFRE OU DE MUDAR A SENHA
			SUBWF OPERACAO, 0
			BTFSS STATUS, Z
			GOTO LOOP_COFRE ;LOOP DO MOTOR, PARA QUE ELE GIRE POR UM TEMPO
			CLRF OPERACAO ; CASO SEJA PARA MUDAR A SENHA, A VARIAVEL OPERACAO SERA USADA COMO CONTADOR
			GOTO INCREMENTA; IR PARA FUNCAO DE INCREMENTA, QUE DIRA PARA QUAL DIGITO SERA GUARDADO O NUMERO QUE O USUARIO DIGITAR
INCREMENTA
			MOVLW d'1' ; INCREMENTANDO + 1 E CHECANDO SE OS 6 DIGITOS DA SENHA NOVA JA FORAM CONTABILIZADOS, CASO SIM, VOLTAR AO MENU
			ADDWF OPERACAO
			MOVLW D'7'
			SUBWF OPERACAO, 0
			BTFSS STATUS, Z
			GOTO CADASTRA_SENHA
			GOTO INICIO

CADASTRA_SENHA
			movlw b'11101111' ; CHECAGEM DOS BOTOES (0 A 9)
			movwf PORTB
			BTFSS PORTB, 0
		GOTO LED01 ; FUNCAO DE CONTABILIZACAO DE VALOR, (NESSE CASO 0)
			BTFSS PORTB, 1
		GOTO LED02
			BTFSS PORTB, 2
		GOTO LED03
			BTFSS PORTB, 3
		GOTO LED04
	
			movlw b'11011111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO LED05
			BTFSS PORTB, 1
		GOTO LED06
			BTFSS PORTB, 2
		GOTO LED07
			BTFSS PORTB, 3
		GOTO LED08

			movlw b'10111111'
			movwf PORTB
			BTFSS PORTB, 0
		GOTO LED09
			BTFSS PORTB, 1
		GOTO LED10
			GOTO CADASTRA_SENHA

		LED01
			BTFSS PORTB, 0 ; TODAS AS FUNCOES DE CONTABILIZACAO DE NOVA SENHA POSSUEM A MESMA LOGICA, ALTERANDO-SE APENAS OS VALORES
			GOTO LED01; ESPERANDO O USUARIO SOLTAR O BOTAO
			CALL PERDE_TEMPO
			CALL CHECAGEM ; CHECAGEM DO DISPLAY, PARA SABER QUAL DIGITO SERA E LIGAR O DISPLAY CORRESPONDENTE AO DIGITO
			movlw b'00111111' ; COLOCANDO O VALOR 0 NO DISPLAY CONTABILIZADO, EM CADA FUNCAO SERA COLOCADO O SEU RESPECTIVO NUMERO
			movwf PORTD
			MOVLW D'1' ; CHECANDO PARA QUAL DIGITO SERA E SALVANDO O VALOR DESSA FUNCAO (0) NA VARIAVEL CORRESPONDENTE AO DIGITO
			SUBWF OPERACAO, 0
			MOVLW D'0'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'0'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'0'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'0'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'0'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6
			CALL PERDE_TEMPO
		GOTO INCREMENTA ; INDO PARA FUNCAO DE INCREMENTACAO, PARA IR PARA CHECAGEM NO PROXIMO DIGITO OU VOLTARAO MENU
		LED02
			BTFSS PORTB, 1
			GOTO LED02
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'00000110'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'1'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'1'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'1'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'1'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'1'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6

			CALL PERDE_TEMPO
		GOTO INCREMENTA
		LED03
			BTFSS PORTB, 2
			GOTO LED03
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'01011011'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'2'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'2'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'2'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'2'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'2'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6
			CALL PERDE_TEMPO
		GOTO INCREMENTA
		LED04
			BTFSS PORTB, 3
			GOTO LED04
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'01001111'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'3'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'3'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'3'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'3'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'3'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6
			CALL PERDE_TEMPO
		GOTO INCREMENTA
		LED05
			BTFSS PORTB, 0
			GOTO LED05
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'01100110'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'4'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'4'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'4'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'4'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'4'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6

			CALL PERDE_TEMPO
		GOTO INCREMENTA
		LED06
			BTFSS PORTB, 1
			GOTO LED06
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'01101101'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'5'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'5'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'5'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'5'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'5'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6
			CALL PERDE_TEMPO
		GOTO INCREMENTA
		LED07
			BTFSS PORTB, 2
			GOTO LED07
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'01111101'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'6'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'6'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'6'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'6'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'6'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6
			CALL PERDE_TEMPO
		GOTO INCREMENTA
		LED08
			BTFSS PORTB, 3
			GOTO LED08
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'00000111'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'7'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'7'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'7'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'7'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'7'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6
			CALL PERDE_TEMPO
		GOTO INCREMENTA
		LED09
			BTFSS PORTB, 0
			GOTO LED09
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'01111111'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'8'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'8'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'8'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'8'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'8'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6
			CALL PERDE_TEMPO
		GOTO INCREMENTA
		LED10
			BTFSS PORTB, 1
			GOTO LED10
			CALL PERDE_TEMPO
			CALL CHECAGEM
			movlw b'01101111'
			movwf PORTD
			MOVLW D'1'
			SUBWF OPERACAO, 0
			MOVLW D'9'
			BTFSC STATUS, Z
				MOVWF c1
			MOVLW D'2'
			SUBWF OPERACAO, 0
			MOVLW D'9'
			BTFSC STATUS, Z
				MOVWF c2
			MOVLW D'3'
			SUBWF OPERACAO, 0
			MOVLW D'9'
			BTFSC STATUS, Z
				MOVWF c3
			MOVLW D'4'
			SUBWF OPERACAO, 0
			MOVLW D'9'
			BTFSC STATUS, Z
				MOVWF c4
			MOVLW D'5'
			SUBWF OPERACAO, 0
			MOVLW D'9'
			BTFSC STATUS, Z
				MOVWF c5
				MOVWF c6
			CALL PERDE_TEMPO
		GOTO INCREMENTA
CHECAGEM
			MOVLW b'00100000' ; CHECANDO EM QUAL DIGITO ESTA ATUALMENTE E ACENDENDO O DISPLAY EQUIVALENTE
			MOVWF PORTA
			MOVLW D'1'
			SUBWF OPERACAO, 0
			BTFSC STATUS, Z
				return
			MOVLW b'00010000'
			MOVWF PORTA
			MOVLW D'2'
			SUBWF OPERACAO, 0
			BTFSC STATUS, Z
				return
			MOVLW b'00001000'
			MOVWF PORTA
			MOVLW D'3'
			SUBWF OPERACAO, 0
			BTFSC STATUS, Z
				return
			MOVLW b'00000100'
			MOVWF PORTA
			MOVLW D'4'
			SUBWF OPERACAO, 0
			BTFSC STATUS, Z
				return
			MOVLW b'00000010'
			MOVWF PORTA
			MOVLW D'5'
			SUBWF OPERACAO, 0
			BTFSC STATUS, Z
				return
			MOVLW b'00000001'
			MOVWF PORTA
				return
LOOP_COFRE
			
			call PERDE_TEMPO_MENOR ; FUNCAO DE PERDE_TEMPO COM MENOS TEMPO PERDIDO PARA QUE O MOTOR GIRE RAPIDO
			CLRF PORTD
			CLRF PORTA

			movlw b'00000001' ; MOVENDO O MOTOR SENTIDO HORARIO
			movwf PORTC

			movlw b'00100000'
			movwf PORTA
			movlw b'01011100' ; O DE OPEN
			movwf PORTD

			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA

			movlw b'00000011'
			movwf PORTC

			movlw b'00010000'
			movwf PORTA
			movlw b'01110011' ; P DE OPEN
			movwf PORTD

			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA


			movlw b'00000010'
			movwf PORTC

			movlw b'00001000'
			movwf PORTA
			movlw b'01111001'; E DE OPEN
			movwf PORTD

			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA


			movlw b'00000110'
			movwf PORTC

			movlw b'00000100'
			movwf PORTA
			movlw b'01010100' ; N DE OPEN
			movwf PORTD

			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA

			movlw b'00000100'
			movwf PORTC

			call PERDE_TEMPO_MENOR


			movlw b'00001100'
			movwf PORTC




			call PERDE_TEMPO_MENOR

			movlw b'00001000'
			movwf PORTC



			call PERDE_TEMPO_MENOR


			movlw b'00001001'
			movwf PORTC


			

			DECFSZ CONTROL,1
			GOTO LOOP_COFRE
			MOVLW D'255' ; LACO DE REPETICAO PARA QUE O MOTOR GIRE POR UM TEMPO
			MOVWF CONTROL
			movlw b'00000000' ; ENQUANTO ESTIVER ABERTO DEVE APITAR
			MOVWF PORTE
			CLRF PORTD
			GOTO WHEN_OPEN

WHEN_OPEN ; ENQUANTO A "PORTA" DO COFRE ESTIVER ABERTA..

			movlw b'00100000'
			movwf PORTA
			movlw b'01011100' ; O DE OPEN
			movwf PORTD
			CALL PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA

			movlw b'00010000'
			movwf PORTA
			movlw b'01110011' ; P DE OPEN
			movwf PORTD
			CALL PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA

			movlw b'00001000'
			movwf PORTA
			movlw b'01111001'; E DE OPEN
			movwf PORTD
			CALL PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA

			movlw b'00000100' 
			movwf PORTA
			movlw b'01010100'; N DE OPEN
			movwf PORTD
			CALL PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA

			movlw b'01111111'
			movwf PORTB
			BTFSC PORTB, 0 ; ABERTA E APITANDO ATE O USUARIO DECIDIR FECHAR (BOTAO C)
			GOTO WHEN_OPEN
			CLRF PORTD	; LIMPANDO O PORT

			movlw b'00000000' ;BIP DE CONFIRMACAO
			MOVWF PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			movlw b'00000001'
			MOVWF PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			movlw b'00000000'
			MOVWF PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			movlw b'00000001'
			MOVWF PORTE
			GOTO CLOSE_COFRE ; FECHAR O COFRE	

CLOSE_COFRE
			BTFSS PORTB, 0 ; AGUARDANDO USUARIO SOLTAR A TECLA, EVITANDO BUGS
			GOTO CLOSE_COFRE
			CALL PERDE_TEMPO_MENOR
			CLRF PORTD ; LIMPANDO O DISPLAY
			CLRF PORTA
			movlw b'00001001' ; MOVENDO O MOTOR SENTIDO ANTI-HORARIO
			movwf PORTC
			movlw b'00100000'
			movwf PORTA
			movlw b'01101101' ; S DE SHUT
			movwf PORTD

			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA
			movlw b'00001000'
			movwf PORTC
			movlw b'00010000'
			movwf PORTA
			movlw b'01110100' ; h DE SHUT
			movwf PORTD


			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA
			movlw b'00001100'
			movwf PORTC
			movlw b'00001000'
			movwf PORTA
			movlw b'00011100' ; u DE SHUT
			movwf PORTD


			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA
			movlw b'00000100'
			movwf PORTC
			movlw b'00000100'
			movwf PORTA
			movlw b'01111000' ; t DE SHUT
			movwf PORTD


			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA
			movlw b'00000110'
			movwf PORTC
			movlw b'00100000'
			movwf PORTA
			movlw b'01101101' ; S DE SHUT
			movwf PORTD



			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA
			movlw b'00000010'
			movwf PORTC
			movlw b'00010000'
			movwf PORTA
			movlw b'01110100' ; h DE SHUT
			movwf PORTD
	

			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA
			movlw b'00000011'
			movwf PORTC
			movlw b'00001000'
			movwf PORTA
			movlw b'00011100' ; u DE SHUT
			movwf PORTD

			
			call PERDE_TEMPO_MENOR
			CLRF PORTD
			CLRF PORTA
			movlw b'00000001'
			movwf PORTC
			movlw b'00000100'
			movwf PORTA
			movlw b'01111000' ; t DE SHUT
			movwf PORTD


			call PERDE_TEMPO_MENOR
			DECFSZ CONTROL,1 ; LACO DE REPETICAO POR ALGUM TEMPO
			goto CLOSE_COFRE
			goto INICIO ; FIM DO LACO, IR PARA INICIO






WRONG
			MOVLW D'1' ; ADCIONANDO +1 NA VARIAVEL DE CONTAGEM DE TENTATIVAS ERRADAS
			ADDWF MAX_TENTATIVA
			MOVLW D'3' ; CHECANDO SE FORAM 3 ERROS SEGUIDOS
			SUBWF MAX_TENTATIVA, 0
			BTFSC STATUS, Z
			GOTO ESTOURO_TENTATIVA ;CASO SIM, DISPARAR UM ALARME
			GOTO ERRO_COMUM ; CASO NAO, DISPARAR APENAS UM AVISO
ERRO_COMUM
			MOVLW d'80' ; MOVER UM VALOR DE TEMPO PARA FICAR NA TELA O AVISO DE ERRO
			MOVWF CONTROL
			GOTO LOOP_ERRO_COMUM
LOOP_ERRO_COMUM
			CALL PERDE_TEMPO ; DURANTE UM TEMPO, COLOCAR NA TELA "nop", PISCANDO, SIMBOLIZANDO O ERRO
			movlw b'00100000'
			movwf PORTA
			movlw b'01010100'
			movwf PORTD
			CALL PERDE_TEMPO
			movlw b'00010000'
			movwf PORTA
			movlw b'00111111'
			movwf PORTD
			CALL PERDE_TEMPO
			movlw b'00001000'
			movwf PORTA
			movlw b'01110011'
			movwf PORTD
			DECFSZ CONTROL,1
			GOTO LOOP_ERRO_COMUM
			GOTO INICIO ; APOS O TEMPO ACABAR, VOLTAR AO INICIO
ESTOURO_TENTATIVA
			movlw b'00100000' ; COLOCAR NO DISPLAY UM RISCO QUE FICARA PISCANDO
			movwf PORTA
			movlw b'01000000'
			movwf PORTD
			MOVLW b'00000001'
			MOVWF PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			movlw b'00100000'
			movwf PORTA
			movlw b'00000000'
			movwf PORTD
			MOVLW b'00000000' ; BUZZER BIPANDO COMO UM ALARME
			MOVWF PORTE
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			CALL PERDE_TEMPO
			DECFSZ CONTROL,1 ; ESPERANDO UM LONGO TEMPO PARA RETORNAR AO NORMAL
			GOTO ESTOURO_TENTATIVA
			CLRF MAX_TENTATIVA ; LIMPANDO A VARIAVEL DE TENTATIVAS ERRADAS
			GOTO INICIO ; IR PARA O INICIO
PERDE_TEMPO
 			MOVLW d'80' 
 			MOVWF VEZES
			CALL LOOP_VEZES
			RETURN
LOOP_VEZES
 			MOVLW d'255'
		 	MOVWF DELAY
 			CALL DELAY_US
 			DECFSZ VEZES,1
 			GOTO LOOP_VEZES
			RETURN
DELAY_US
 			NOP
 			NOP
 			DECFSZ DELAY,1
 			GOTO DELAY_US
 			RETURN
		
PERDE_TEMPO_MENOR
 			MOVLW d'50'
 			MOVWF VEZES
			CALL LOOP_VEZES_MOTOR
			RETURN
LOOP_VEZES_MOTOR
 			MOVLW d'50'
		 	MOVWF DELAY
 			CALL DELAY_US
 			DECFSZ VEZES,1
 			GOTO LOOP_VEZES_MOTOR
			RETURN
DELAY_US_MOTOR
 			NOP
 			NOP
 			DECFSZ DELAY,1
 			GOTO DELAY_US
 			RETURN		

END
